### PR TITLE
Updated utils to prevent errors on Django master

### PR DESCRIPTION
**Pull request by kezabelle**
- Django 1.9 will drop `django.utils.importlib` in favour of the stdlib's version.
- Django 1.8 changes the way the standard loaders work, because of the multiple-template engine changes. The change to instantiating the loader should work for DjangoTemplates, though I have no idea if it'd work for others.

### CODE REVIEW

**Comment by centralniak** [comment]
Thanks for your work! 

There is a couple of things we could try to improve here

* add `importlib` as a dependency - as it's only valid for some installations, perhaps it would be enough to just document it in `README.rst`?
* bump the version

I'll have a look into logic this week.

**Comment by kezabelle** [comment]
> add importlib as a dependency - as it's only valid for some installations

- Django `1.7+` requires python `2.7` or `3.2+` all of which should have the python stdlib `importlib`
- Django `1.6.x` requires python `2.6.5` or `3.2+`, and defaults to using the python stdlib `importlib` for `3.2+`, falling back to it's own backport of `import_module` for python `2.6+`
- Django `1.5.x` requires python `2.6.5` and has experimental support for `3.2+`, and always uses the Django backport of `import_module`
- Django `1.4.x` requires python `2.5+`, without any `3.x` support, and uses the backport of `import_module` always.

As far as I can reason out, the `try/except` should cover pretty much every valid installation you could be expected to support.

**Comment by centralniak** [comment]
Oh, you're right! Sorry, I was missing the point about `importlib`. 

So now we'll possibly just want to add tox / travis config for recent Django /  Python versions.

**Comment by centralniak** [comment]
Right, so I've run the test suite and got following results:

```
________________________________________________ summary ________________________________________________
ERROR:   py3.4-django1.7: commands failed
ERROR:   py3.3-django1.7: commands failed
ERROR:   py2.7-django1.7: commands failed
  py3.4-django1.6: commands succeeded
  py3.3-django1.6: commands succeeded
  py2.7-django1.6: commands succeeded
  py2.6-django1.6: commands succeeded
  py3.3-django1.5: commands succeeded
  py2.7-django1.5: commands succeeded
  py2.6-django1.5: commands succeeded
  py2.7-django1.4: commands succeeded
  py2.6-django1.4: commands succeeded
  py2.7-django1.3: commands succeeded
  py2.6-django1.3: commands succeeded
```

I guess we might want to address the Django 1.7 issues?

Here is a stack trace from Django 1.7 / Python 3.4 run:

```
======================================================================
ERROR: test_explicit_name (templatefinder.tests.AppDirectoriesLoaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/piotr/Opensource/django-template-finder/templatefinder/tests.py", line 10, in test_explicit_name
    self.assertEqual(['404.html'], find_all_templates('404.html'))
  File "/home/piotr/Opensource/django-template-finder/templatefinder/utils.py", line 64, in find_all_templates
    loader_class = getattr(import_module(module), klass)
  File "/home/piotr/.virtualenvs/django-template-finder/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/piotr/.virtualenvs/django-template-finder/lib/python3.4/site-packages/django/template/loaders/app_directories.py", line 33, in <module>
    app_template_dirs = calculate_app_template_dirs()
  File "/home/piotr/.virtualenvs/django-template-finder/lib/python3.4/site-packages/django/template/loaders/app_directories.py", line 21, in calculate_app_template_dirs
    for app_config in apps.get_app_configs():
  File "/home/piotr/.virtualenvs/django-template-finder/lib/python3.4/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/piotr/.virtualenvs/django-template-finder/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Do you have any idea how to address this? Perhaps we need to adjust `runtests.py`? If not I should be able to help with this.

**Comment by kezabelle** [comment]
Off the top of my head, I believe that:
```
if hasattr(django, 'setup'):
    django.setup()
```
will be necessary in `runtests.py` (after `django.configure`) to run the tests on `1.7+`, because of the appconfig refactor

**Comment by centralniak** [comment]
Cheers. I'll try that.

**Comment by centralniak** [comment]
Awesome! I have rebased this `origin/master` and all went well this time. As I cannot push to your PR, I'm opening a separate one and merging this in right away. 

Many thanks for this fix! :bow:

**Pull request closed without merging**
